regions:
  -
    id: 1
    name: southeast asia
    monsters:
      -
        id: 1
        total: 1
        position:
          min_x: 10
          max_x: 20
          min_y: 10
          max_y: 20
    towns:
      -
        id: 1
        spawn_position:
          x: 5
          y: 5
        portal:
          min_x: 15
          max_x: 18
          min_y: 15
          max_y: 18
