regions:
  -
    id: 1
    name: southeast asia
    towns:
      -
        id: 1
        spawn_position:
          x: 5
          y: 5
        portal:
          min_x: 0
          max_x: 6
          min_y: 11
          max_y: 14
